export const skills = [
  "Information Security",
  "Cybersecurity",
  "ISMS",
  "ISO/IEC 27001:2022",
  "Governance, Risk & Compliance (GRC)",
  "Vulnerability Assessment",
  "Penetration Testing (VAPT)",
  "Secure SDLC",
  "CrowdStrike Falcon",
  "Trend Micro",
  "DPDP Compliance",
  "Incident Management",
  "Business Continuity Planning",
  "Disaster Recovery",
  "Security Architecture Review",
  "Access Reviews",
  "Transaction Reviews",
  "Risk Assessment",
  "AWS",
  "Documentation",
];